site_name: TripKit SDK for Android
nav:
  - Introduction: index.md
  - TripKit Map Fragment: tripkit_map_fragment.md
  - Searching for a Location: search_location.md
  - Trip Results: trip_results.md
  - Service & Stop Detail: stop_detail.md
  - Class Documentation: tripkit-android/index.md
theme:
    name: null
    custom_dir: ../skedgo_theme/
    language: en
    extra_css:
      - 'stylesheets/extra.css'
    palette:
      primary: 'rgb(21, 76, 123)'
      accent: 'indigo'
    font:
      text: Roboto
      code: Roboto Mono
    logo: 'img/tripgo-api-logo-white.svg'
    feature:
      tabs: false
    include_search_page: false
    search_index_only: false
    static_templates:
      - 404.html

markdown_extensions:
  - admonition
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight:
      css_class: codehilite
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

